---
platform: linux

image_resource:
  type: registry-image
  source: 
    repository: ubuntu
    tag: 18.04

run:
  path: automate_allthethings/scripts/create_opsman_config.sh
  user: root

inputs:
- name: automate_allthethings

outputs:
- name: opsmanconfig-output

