---
platform: linux

image_resource:
  type: registry-image
  source: 
    repository: ubuntu
    tag: 18.04

run:
  path: automate_allthethings/scripts/pave_iaas.sh
  user: root

params:
  ACCESS_KEY: ((access_key_id))
  SECRET_KEY: ((secret_access_key))


inputs:
- name: automate_allthethings
- name: tf_iaas


outputs:
- name: terraform-output

